version: '3'

services:
  app:
    build: .
    command: ["./scripts/wait-for-it.sh", "db:6379", "--", "./scripts/run.sh"]
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_EXPIRATION=${REDIS_EXPIRATION}
    volumes:
      - .:/go/src/github.com/cfx-cv/trail:z
    ports:
      - "3002:8000"
    depends_on:
      - db

  db:
    image: redis:4.0
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
