version: '3'

services:
  app:
    build: .
    command: ./app
    volumes:
      - .:/go/src/app:z
    ports:
      - "3002:8000"
    depends_on:
      - db

  db:
    image: redis:4.0
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
